# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Publish package to GitHub Packages

on:
  workflow_dispatch:
    inputs:
      version:
        description: '배포 버전을 명시하세요.'     
        required: true
  release:
    types: [created]
    paths:
      - 'checkstyle/spring-data-jpa/**'  

defaults:
  run:
    working-directory: checkstyle/spring-data-jpa

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish package
        run: |
          # NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3 | cut -d "v" -f2)
          NEW_VERSION=${{github.event.inputs.name}}
          echo "New version: ${NEW_VERSION}"
          echo "Github username: ${GITHUB_ACTOR}"
          ./gradlew -Pversion=${NEW_VERSION} publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
